### ISSUE TITLE
emote in chat

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/jub.dj#10]
Steps to recreate issue:
1. send a chat message in the format /me [message text]

What I expected to happen:
/me [message text] should change the message displayed from [username]: [message text] to <i>[username]</i> [message text]

What actually happened:
/me [message text] was displayed as [username]: [message text]

**Comment by aromatt** [comment]
Implemented by https://github.com/aromatt/jub.dj/commit/bf3833b1e966d7663497490a5566b49ee838f9e4

**Comment by acowinthecrowd** [comment]
This might need to be reopened
![image](https://cloud.githubusercontent.com/assets/10477478/10239543/2d3282cc-689d-11e5-9c99-32822c72d27c.png)

**Comment by aromatt** [comment]
I hadn't restarted the server yet. Try it now!
