### ISSUE TITLE
search youtube from within jub.dj

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/jub.dj#12]
Steps to recreate:
1. Locate a way to search youtube's video library and load a video without leaving the jub.dj interface

What I expected to happen:
A search box that ties to youtube's library would be available, and when search terms are passed to it, matching videos from youtube's library are displayed. From there I could select a video to play.

What actually happened:
Unable to locate a search box that does this

**Comment by aromatt** [comment]
implemented by https://github.com/aromatt/jub.dj/commit/bfd182482872772d2c5c0d370ece796121b93aef
