### ISSUE TITLE
Ensure chat history ("messages" element) does not collide with other controls when browser zoom level changes

### ISSUE THREAD

**Issue by croasus** [aromatt/jub.dj#14]
Steps to recreate: 
1) At 1366 x 768 resolution, open jub.dj page in Chrome browser
2) Zoom to 100% within Chrome (ctrl +    or    ctrl -  )
3) Type in a bunch of chat messages so that history is full

What I see:
The messages list / chat history extends under the text input / send button controls (see attached picture).

What I expect to see:
The bottom of the messages list element stops before the text input / send button controls

![chat history collide](https://cloud.githubusercontent.com/assets/3858269/10166067/5efd69f2-6690-11e5-9f90-61bf26405552.png)

**Comment by aromatt** [comment]
https://github.com/aromatt/jub.dj/commit/8ad1d36bc8410e8ee89153331c33e1e2671288ad
