### ISSUE TITLE
no visual indicator that video is muted

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/jub.dj#15]
Steps to recreate:
1. ensure a video is playing
2. mute video

what I expected:
A mute symbol appear, the color of the mute button would change, or some other visual indication that the video had been muted would appear

what happened:
no visual indicator was displayed

**Comment by aromatt** [comment]
Fixed by https://github.com/aromatt/jub.dj/commit/01b78f7cd31cc31118d212b28d9bf4b4e85ae4df
