### ISSUE TITLE
Timestamp on chat messages

### ISSUE THREAD

**Issue by baronpumpky** [aromatt/jub.dj#16]
Add a timestamp on chat messages in the chat log.

**Comment by aromatt** [comment]
https://github.com/aromatt/jub.dj/commit/67d38c65ad3481720df0595c4192c71ca464202b

**Comment by jeskaeli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#168: Separate "latest updates" from chat history and add expiration](https://trello.com/c/IF8rBoVw/43-168-separate-latest-updates-from-chat-history-and-add-expiration)
