### ISSUE TITLE
shouldn't be able to post chat message without a username

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/jub.dj#21]
Steps to recreate
1. Empty the username field
2. press submit
3. sent chat message

what i expect to happen
Error pops up saying you must set a username to chat

what actually happens
chat message is sent with no username attached

**Comment by aromatt** [comment]
This issue will be shaken out anyway once we have a full-blown log-in system, but it will be really easy to put this in place in the meantime.  The client is responsible for sending up their username with their chat message anyway, so just don't send the message if the username is not defined.

**Comment by aromatt** [comment]
Fixed by https://github.com/aromatt/jub.dj/commit/857a119ed5b7a385042394e01b779b5db70989b3
