### ISSUE TITLE
Chat window overlaps video player at skinnier display widths

### ISSUE THREAD

**Issue by baronpumpky** [aromatt/jub.dj#25]
Chat window overlaps video player at skinnier display widths:
![overlappingchat](https://cloud.githubusercontent.com/assets/4427385/10196261/9dbb85ee-6757-11e5-992c-c3a9abfb3e67.PNG)

**Comment by aromatt** [comment]
I think this is a duplicate of #14.

**Comment by aromatt** [comment]
Oops, no it's not.

**Comment by baronpumpky** [comment]
This is fixed in latest.
