### ISSUE TITLE
Extend chat line color per person for all subsequent messages, remove duplicated username

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/jub.dj#28]
As long as the same person is sending messages, instead of alternating each line, keep the same dark or light background. Also, only display username for the first line of the sequence.

![chats](https://cloud.githubusercontent.com/assets/14909827/10199852/f1578798-6770-11e5-8ffb-c9c3dbc34809.png)

**Comment by aromatt** [comment]
good call.

**Comment by jeskaeli** [comment]
How about we also make the usernames <b>bold</b>?

**Comment by croasus** [comment]
I will work on this

**Comment by aromatt** [comment]
user names are now bold
