### ISSUE TITLE
Add link to the github on the main page for easy reporting

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/jub.dj#31]
Rather than users having to keep track of this page, provide a small (temporary) link somewhere on the page that takes the user to the list of issues in a new tab. This could make it more convenient for users to report issues during this initial stage. Here are examples of three places this could appear:

![report](https://cloud.githubusercontent.com/assets/14909827/10202233/efc3f8b4-677d-11e5-9f63-144673c9b132.png)

**Comment by aromatt** [comment]
@jeskaeli props for the screenshot

**Comment by aromatt** [comment]
Implemented by https://github.com/aromatt/jub.dj/commit/6edfaa048eddb9b377ea8e33337b38b15a2f508a
