### ISSUE TITLE
Change "Who's Here:" label of online users to "Jubs Here:" or "Who's Jubbin:" or similar

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/jub.dj#37]
Steps to recreate
1. open jub.dj
2. look at online users: label

what i expect to happen
I see some reference to jubs or jubbing

what actually happens
A boring title

**Comment by aromatt** [comment]
This may fall flat but:
This is a super easy fix (see line https://github.com/aromatt/jub.dj/blob/master/views/menu.jade#L10).  I see you've already forked the project... would you be interested in making the change and submitting a pull request? you could even do it from your browser.

**Comment by acowinthecrowd** [comment]
I'll try. I def don't want to have to download any compilers or editors. I
looked at trying to change the mute button color but I couldn't change any
code in the browser.

**Comment by aromatt** [comment]
You should be able to edit code in your fork (https://github.com/acowinthecrowd/jub.dj) in the browser, and commit the changes from there.  The only problem is that your fork is out of date now, so you'd need to pull from mine.  @croasus, do you have a windows git workflow that you like?

**Comment by croasus** [comment]
I like github for windows: https://github-windows.s3.amazonaws.com/GitHubSetup.exe. Could just use notepad as the editor. 

BUT if you're just doing everything in the browser then I don't think you need a windows workflow.

**Comment by aromatt** [comment]
Implemented by https://github.com/aromatt/jub.dj/commit/3d1da2aaae306f22be9bb20e125e2cfb48952c6c
