### ISSUE TITLE
Do not refocus the chat to the most recent message on receipt of every message

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/jub.dj#38]
Allow users to scroll up and read older chat messages without being jerked back down to the newest message every time one is received

**Comment by jeskaeli** [comment]
This has been fixed for some, but this is now broken in Chrome. Chat does not refocus even when scrolled to the bottom - a much worse scenario!

**Comment by jeskaeli** [comment]
@aromatt Update: I've confirmed other people can use Chrome in Windows 7 and are NOT experiencing this problem. I don't know what is causing it, but I've refreshed multiple times and restarted my computer. My chat window does NOT scrolll with new messages under any circumstances (unless I use Firefox). Maybe it has to do with the component size? IDK

**Comment by aromatt** [comment]
I'll need to test this some more but I think it's workable now.  Basically the line that checked whether or not you were at the bottom already was not working because for some reason, for some people, it's NOT at the exact bottom, by a fraction of a pixel.

**Comment by aromatt** [comment]
fairly confident this is fixed now, we'll reopen if it comes back for anyone.
