### ISSUE TITLE
Turn off autocomplete in the chat input field

### ISSUE THREAD

**Issue by baronpumpky** [aromatt/jub.dj#41]
When you start typing a message that matches the string(s) of a previous message/messages, the chat field will suggest those past messages. This just comes across as kind of odd and isn't really useful. Should be able to disable that easily on the input field

**Comment by acowinthecrowd** [comment]
Mine doesn't have autocomplete

**Comment by aromatt** [comment]
hopefully fixed by https://github.com/aromatt/jub.dj/commit/bfd182482872772d2c5c0d370ece796121b93aef
