### ISSUE TITLE
Account for wrapping long strings of text

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/jub.dj#42]
Long strings of text need to wrap so that a horizontal scrollbar isn't displayed:

![2xscroll](https://cloud.githubusercontent.com/assets/14909827/10252143/887f92ee-6903-11e5-9788-f793da759a8a.jpg)

**Comment by acowinthecrowd** [comment]
+1

**Comment by aromatt** [comment]
There's another wrap-related bug: when the content DOES wrap, the method we're using to determine whether the user was already scrolled to the bottom breaks -- My hypothesis is that one of the two properties we're comparing to each other accounts for it, and the other does not.

**Comment by croasus** [comment]
I will work on this
