### ISSUE TITLE
Post song title, DJ, and link to source in chat when a new song starts

### ISSUE THREAD

**Issue by csumsky3** [aromatt/jub.dj#44]
This was something I always wanted in plug. It happens often that a song is playing and people are like "Man i love this song", but then someone else doesn't see it until like 15 minutes later and they're all like, "which song were you talking about?" 

So if every time a new song started, it logged to the chat thread, you could just look at the last song started to see what they are referring to.

DJ and link to source are sorta nice-to-haves, but yea that's the general idea.

**Comment by aromatt** [comment]
aah, yes, this is a great idea.

**Comment by aromatt** [comment]
implemented by https://github.com/aromatt/jub.dj/commit/61afc3a476007ab3759e5e23da75be946072698a
