### ISSUE TITLE
mute setting should be persistent when exiting and coming back

### ISSUE THREAD

**Issue by acowinthecrowd** [aromatt/jub.dj#50]
Recreate
1. Open jub.dj
2. mute sound
3. close jub.dj
4. open jub.dj

what i expect
Sound is still muted when reopened

what happens
sound is no longer muted

**Comment by aromatt** [comment]
implemented in https://github.com/aromatt/jub.dj/commit/3bfc953e3ad7deb839bcf340752946c9c861a2ad
