### ISSUE TITLE
Remove jubbot from Who's Jubbin list

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/jub.dj#59]
Remove jubbot from the list; it's confusing and makes me feel like I'm being watched.

**Comment by aromatt** [comment]
I think over time you'll see him earn his spot on the list, as we add his useful/fun features.  Months ago we wanted to connect a chat bot into the old room but never got around to it.  Now we've got one and I think it would be inconsistent with the rest of the chat interface if he wasn't on the list -- consider that we can address the bot like we can address each other, and its messages appear in the chat window along with ours.

**Comment by jeskaeli** [comment]
Ok, I'm on board. Feel free to close this one!
