### ISSUE TITLE
Some playlists aren't posting to the queue 

### ISSUE THREAD

**Issue by csumsky3** [aromatt/jub.dj#62]
Tried to post this playlist to the queue https://www.youtube.com/playlist?list=PLQz_l7RxEIw1tXTvm_j9Ww-xFkSwOP5C5, but it no worky. You said "nothing to see in the logs, it's acting like nothing came back when it asked for that playlistId, but no errors."

**Comment by aromatt** [comment]
This appears to be fixed with the latest playlist updates
