### ISSUE TITLE
DJ button toggles upon refresh

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/jub.dj#73]
The DJ button changes from green headphones back to purple on refresh. (I am still DJing - only the button is incorrect).

**Comment by aromatt** [comment]
I think with this fix, we'll switch over to central storage and stop relying on cookies.  Otherwise user states is only going to get more confusing.

**Comment by aromatt** [comment]
on second thought, since DJ state is already stored on the server, this should be easy to fix before switching to a database, and it's a pretty big bug so I'll go ahead and do that.

**Comment by acowinthecrowd** [comment]
What about #30 then?

**Comment by aromatt** [comment]
I'll see about this next

**Comment by aromatt** [comment]
I guess I meant I'll see about #30.
