### ISSUE TITLE
Emoting is broken in chat

### ISSUE THREAD

**Issue by jeskaeli** [aromatt/jub.dj#80]
if I have no prior messages, I can emote; but then all my subsequent messages are also in 'emote' style. If my emote would appear subsequent to a previous message of mine, the emote style is not applied.

![chatemote](https://cloud.githubusercontent.com/assets/14909827/10483025/d28bf2f6-724a-11e5-8fd0-0647118766a4.png)

**Comment by aromatt** [comment]
haha
